import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Translation data
const translations = {
  en: {
    home: 'Home',
    about: 'About',
    services: 'Services',
    team: 'Team',
    contact: 'Contact',
    login: 'Login',
    signup: 'Sign Up',
    dashboard: 'Dashboard',
    logout: 'Logout',
    getVerified: 'Get Verified',
    language: 'Language',
    // Team page translations
    ourTeam: 'Our Team',
    peopleBehindMission: 'People behind the mission — building trusted, compliant, and scalable verification experiences.',
    weBuildWithTrust: 'We build with trust at the core',
    teamBlendsStrategy: 'Our team blends strategy, creativity, and technology to deliver verification experiences that are fast, compliant, and human-centered.',
    workWithUs: 'Work with us',
    seeWhatWeDo: 'See what we do',
    call: 'Call',
    available: 'Available 9am–6pm',
    // SuperAdmin dashboard translations
    superAdminDashboard: 'Super Admin Dashboard',
    welcomeBack: 'Welcome back',
    userStatistics: 'User Statistics',
    quickActions: 'Quick Actions',
    totalUsers: 'Total Users',
    otherSuperAdmins: 'Other Super Admins',
    admins: 'Admins',
    regularUsers: 'Regular Users',
    activeUsers: 'Active Users',
    inactiveUsers: 'Inactive Users',
    createNewAdmin: 'Create New Admin',
    manageUsers: 'Manage Users',
    viewContacts: 'View Contacts',
    heroTitle: 'Secure Background Verification Made Simple',
    heroSubtitle: 'Trust, verify, and hire with confidence.',
    getStarted: 'Get Started',
    learnMore: 'Learn More',
    welcomeBack: 'Welcome back',
    overview: 'Overview',
    userManagement: 'User Management',
    contactManagement: 'Contact Management',
    quickActions: 'Quick Actions',
    yourProfile: 'Your Profile',
    totalUsers: 'Total Users',
    activeUsers: 'Active Users',
    inactiveUsers: 'Inactive Users',
    createNewAdmin: 'Create New Admin',
    manageUsers: 'Manage Users',
    viewContacts: 'View Contacts',
    name: 'Name',
    username: 'Username',
    role: 'Role',
    status: 'Status',
    accountType: 'Account Type',
    googleAccount: 'Google Account',
    regularAccount: 'Regular Account',
    searchUsers: 'Search by name, email, or username...',
    show: 'Show',
    actions: 'Actions',
    activate: 'Activate',
    deactivate: 'Deactivate',
    delete: 'Delete',
    edit: 'Edit',
    view: 'View',
    confirmDeletion: 'Confirm Deletion',
    thisActionCannotBeUndone: 'This action cannot be undone',
    deleteUser: 'Delete User',
    deleteAdmin: 'Delete Admin',
    deleteContact: 'Delete Contact',
    areYouSureDelete: 'Are you sure you want to delete',
    cancel: 'Cancel',
    close: 'Close',
    loading: 'Loading...',
    next: 'Next',
    previous: 'Previous',
    fullName: 'Full Name',
    email: 'Email',
    phone: 'Phone',
    message: 'Message',
    sendMessage: 'Send Message',
    contactInfo: 'Contact Information',
    address: 'Address',
    phoneNumber: 'Phone Number',
    contactTitle: 'Contact Us',
    contactSubtitle: 'Get in touch with us for any inquiries',
    aboutTitle: 'About Us',
    aboutSubtitle: 'Hiresheild is a fast-growing startup revolutionizing the background verification landscape.',
    servicesTitle: 'Our Services',
    servicesSubtitle: 'Comprehensive background verification solutions for your business needs',
    criminalCheck: 'Criminal Background Check',
    educationVerification: 'Education Verification',
    employmentHistory: 'Employment History',
    addressVerification: 'Address Verification',
    whyChooseUs: 'Why Choose Us',
    fastVerification: 'Fast Verification',
    secureData: 'Secure Data',
    comprehensiveChecks: 'Comprehensive Checks',
    trustedBy: 'Trusted by leading companies',
    allRightsReserved: 'All rights reserved',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    emailAddress: 'Email Address',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    firstName: 'First Name',
    lastName: 'Last Name',
    forgotPassword: 'Forgot Password?',
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: 'Already have an account?',
    signUp: 'Sign Up',
    signIn: 'Sign In',
    profileUpdated: 'Profile updated successfully!',
    passwordChanged: 'Password changed successfully!',
    passwordsDoNotMatch: 'New passwords do not match!',
    adminCreated: 'Admin created successfully!',
    userRoleUpdated: 'User role updated successfully!',
    userStatusUpdated: 'User status updated successfully!',
    userDeleted: 'User deleted successfully!',
    contactDeleted: 'Contact submission deleted successfully!',
    contactSubmitted: 'Contact form submitted successfully!',
    changePassword: 'Change Password',
    updateProfile: 'Update Profile',
    // HomePage additional translations
    secure: 'Secure',
    compliant: 'Compliant',
    verified: 'Verified',
    trust: 'trust',
    fast: 'fast',
    reliable: 'reliable',
    precision: 'precision',
    transparency: 'transparency',
    care: 'care',
    verificationsCompleted: 'Verifications Completed',
    uptimeAvailability: 'Uptime & Availability',
    support: 'Support',
    securityCompliance: 'Security & Compliance',
    fastReliable: 'Fast & Reliable',
    fastReliableDesc: 'Industry-leading turnaround with precise, auditable results you can trust.',
    compliantByDesign: 'Compliant by Design',
    compliantByDesignDesc: 'Built for security and regulatory alignment across industries and geographies.',
    scalesWithYou: 'Scales with You',
    scalesWithYouDesc: 'From startups to enterprises, integrate into your workflows effortlessly.',
    servicesDescription: 'From employment history and education checks to criminal records and identity verification, we offer a full spectrum of services tailored to your industry.',
    employmentHistory: 'Employment History',
    educationChecks: 'Education Checks',
    criminalRecords: 'Criminal Records',
    identityVerification: 'Identity Verification',
    addressVerification: 'Address Verification',
    globalSanctions: 'Global Sanctions',
    comprehensiveScreening: 'Comprehensive screening powered by modern data sources and secure automation.',
    learnMore: 'Learn more →',
    howItWorks: 'How it works',
    initiate: '1. Initiate',
    initiateDesc: 'Create a check and invite candidates securely via our platform.',
    verify: '2. Verify',
    verifyDesc: 'We verify with trusted sources and keep you updated in real-time.',
    decide: '3. Decide',
    decideDesc: 'Receive a clear, compliant report to make confident decisions.',
    buildSaferWorkplaces: 'Build safer workplaces and stronger teams',
    oneVerifiedProfile: 'One verified profile at a time. Start your next verification in minutes.',
    getStarted: 'Get Started',
    talkToUs: 'Talk to us',
    // ContactPage additional translations
    haveQuestions: 'Have questions or need assistance? We\'d love to hear from you. Send us a message and we\'ll respond as soon as possible.',
    companyInformation: 'Company Information',
    pleaseProvideCompany: 'Please provide your company details (optional)',
    companyName: 'Company Name',
    companyPhone: 'Company Phone',
    companyEmail: 'Company Email',
    companyAddress: 'Company Address',
    enterCompanyName: 'Enter your company name',
    enterCompanyPhone: 'Enter company phone number',
    enterCompanyEmail: 'Enter company email address',
    enterCompanyAddress: 'Enter company address',
    businessHours: 'Our Business Hours',
    mondayFriday: 'Monday - Friday',
    saturday: 'Saturday',
    sunday: 'Sunday',
    closed: 'Closed',
    emergencySupport: 'Emergency Support:',
    available247: 'Available 24/7 for critical issues',
    // LoginPage additional translations
    signInToAccount: 'Sign in to your account',
    welcomeBackContinue: 'Welcome back. Please sign in to continue.',
    enterEmail: 'Enter your email',
    enterPassword: 'Enter your password',
    orContinueWith: 'Or continue with',
    continueWithGoogle: 'Continue with Google',
    dontHaveAccount: 'Don\'t have an account?',
    signUp: 'Sign up',
    byContinuing: 'By continuing, you agree to our',
    termsOfService: 'Terms of Service',
    and: 'and',
    // SignupPage additional translations
    joinUs: 'Join Us',
    createAccountStarted: 'Create your account to get started',
    createAccount: 'Create Account',
    step1Basic: 'Step 1: Basic Information',
    step2Security: 'Step 2: Security Setup',
    username: 'Username',
    chooseUsername: 'Choose a username',
    firstName: 'First Name',
    lastName: 'Last Name',
    first_name: 'First name',
    last_name: 'Last name',
    continue: 'Continue',
    createStrongPassword: 'Create a strong password',
    confirmPassword: 'Confirm Password',
    confirmYourPassword: 'Confirm your password',
    creatingAccount: 'Creating Account...',
    processing: 'Processing...',
    signUpWithGoogle: 'Sign up with Google',
    alreadyHaveAccount: 'Already have an account?',
    signIn: 'Sign in',
    // Dashboard translations
    quickActions: 'Quick Actions',
    yourProfile: 'Your Profile',
    totalUsers: 'Total Users',
    activeUsers: 'Active Users',
    inactiveUsers: 'Inactive Users',
    createNewAdmin: 'Create New Admin',
    manageUsers: 'Manage Users',
    viewContacts: 'View Contacts',
    accountType: 'Account Type',
    googleAccount: 'Google Account',
    regularAccount: 'Regular Account',
    searchUsers: 'Search by name, email, or username...',
    show: 'Show',
    actions: 'Actions',
    activate: 'Activate',
    deactivate: 'Deactivate',
    delete: 'Delete',
    edit: 'Edit',
    view: 'View',
    confirmDeletion: 'Confirm Deletion',
    thisActionCannotBeUndone: 'This action cannot be undone',
    deleteUser: 'Delete User',
    deleteAdmin: 'Delete Admin',
    deleteContact: 'Delete Contact',
    areYouSureDelete: 'Are you sure you want to delete',
    cancel: 'Cancel',
    close: 'Close',
    loading: 'Loading...',
    next: 'Next',
    previous: 'Previous',
    fullName: 'Full Name',
    phone: 'Phone',
    message: 'Message',
    sendMessage: 'Send Message',
    contactInfo: 'Contact Information',
    address: 'Address',
    phoneNumber: 'Phone Number',
    contactTitle: 'Contact Us',
    contactSubtitle: 'Get in touch with us for any inquiries',
    aboutTitle: 'About Us',
    aboutSubtitle: 'Hiresheild is a fast-growing startup revolutionizing the background verification landscape.',
    servicesTitle: 'Our Services',
    servicesSubtitle: 'Comprehensive background verification solutions for your business needs',
    criminalCheck: 'Criminal Background Check',
    educationVerification: 'Education Verification',
    whyChooseUs: 'Why Choose Us',
    fastVerification: 'Fast Verification',
    secureData: 'Secure Data',
    comprehensiveChecks: 'Comprehensive Checks',
    trustedBy: 'Trusted by leading companies',
    allRightsReserved: 'All rights reserved',
    privacyPolicy: 'Privacy Policy',
    emailAddress: 'Email Address',
    forgotPassword: 'Forgot Password?',
    profileUpdated: 'Profile updated successfully!',
    passwordChanged: 'Password changed successfully!',
    passwordsDoNotMatch: 'New passwords do not match!',
    adminCreated: 'Admin created successfully!',
    userRoleUpdated: 'User role updated successfully!',
    userStatusUpdated: 'User status updated successfully!',
    userDeleted: 'User deleted successfully!',
    contactDeleted: 'Contact submission deleted successfully!',
    contactSubmitted: 'Contact form submitted successfully!',
    // Services translations
    aadhaarVerification: 'Aadhaar Verification',
    aadhaarVerificationDesc: 'Validate Aadhaar numbers and documents securely.',
    panVerification: 'PAN Verification',
    panVerificationDesc: 'Verify PAN details with strict privacy controls.',
    passportVerification: 'Passport Verification',
    passportVerificationDesc: 'Confirm passport validity and identity information.',
    employmentChecksDesc: 'Background checks for employment screening.',
    addressVerificationDesc: 'Confirm addresses with proof and geotagging.',
    criminalRecordsCheck: 'Criminal Records Check',
    criminalRecordsCheckDesc: 'Risk assessment via authorized sources.',
     // About page translations
    aboutDescription: 'Hiresheild is a fast-growing startup revolutionizing the background verification landscape with smart, scalable, and secure solutions. Founded in 2025 and headquartered in Bengaluru, Hiresheild was born out of a vision to simplify trust-building in hiring and onboarding processes for modern businesses. By combining automation, AI-driven analytics, and a mobile-first approach, Hiresheild delivers rapid, reliable, and compliant verification services tailored for startups, SMEs, and enterprise clients.',
    buildingTrustThroughInnovation: 'Building trust through innovation',
    buildingTrustDescription: 'We\'re on a mission to transform how organizations verify and trust their people, making the process faster, more secure, and completely transparent.',
    getStarted: 'Get Started',
    ourServices: 'Our Services',
    trustedByCompanies: 'Trusted by 100+ companies',
    mission: 'Mission',
    missionDescription: 'To make background verification seamless, transparent, and accessible for every organization—regardless of size or industry.',
    vision: 'Vision',
    visionDescription: 'To become the most agile and trusted background verification partner for the digital-first economy.',
    values: 'Values',
    valuesDescription: 'Privacy, security, transparency, and customer success drive everything we do.',
    whyChooseHiresheild: 'Why Choose Hiresheild?',
    fastEfficient: 'Fast & Efficient',
    fastEfficientDesc: 'AI-powered verification that\'s 10x faster than traditional methods',
    secureCompliant: 'Secure & Compliant',
    secureCompliantDesc: 'Enterprise-grade security with full regulatory compliance',
    mobileFirst: 'Mobile-First',
    mobileFirstDesc: 'Built for the modern workforce with seamless mobile experience',
    scalableSolution: 'Scalable Solution',
    scalableSolutionDesc: 'Grows with your business from startup to enterprise',
    // Team page member bios
    kumarJagannathBio: 'Kumar is a dynamic business leader with years of experience in strategy, operations, and client engagement. Known for an analytical mindset and collaborative leadership, he has led communication and tech startups and digital media firms. He solves complex problems with simple, scalable solutions and mentors professionals navigating career transitions.',
    divyaMuruganBio: 'Divya is a results-driven strategist with a strong background in brand development, digital campaigns, and consumer insights. Recognized for creative thinking and data-informed decisions, she thrives in fast-paced environments and builds narratives that connect deeply with audiences.',
  },
  
  ta: {
    home: 'முகப்பு',
    about: 'எங்களைப் பற்றி',
    services: 'சேவைகள்',
    team: 'அணி',
    contact: 'தொடர்பு',
    login: 'உள்நுழைவு',
    signup: 'பதிவு செய்க',
    dashboard: 'டாஷ்போர்டு',
    logout: 'வெளியேறு',
    getVerified: 'சரிபார்க்கப்பட்டது',
    language: 'மொழி',
    // Team page translations
    ourTeam: 'எங்கள் அணி',
    peopleBehindMission: 'பணியின் பின்னால் உள்ள மக்கள் — நம்பகமான, இணக்கமான மற்றும் அளவிடக்கூடிய சரிபார்ப்பு அனுபவங்களை உருவாக்குகிறார்கள்.',
    weBuildWithTrust: 'நாங்கள் நம்பிக்கையுடன் கட்டமைக்கிறோம்',
    teamBlendsStrategy: 'எங்கள் அணி உத்தி, படைப்பாற்றல் மற்றும் தொழில்நுட்பத்தை கலந்து வேகமான, இணக்கமான மற்றும் மனித-மையமான சரிபார்ப்பு அனுபவங்களை வழங்குகிறது.',
    workWithUs: 'எங்களுடன் வேலை செய்யுங்கள்',
    seeWhatWeDo: 'நாங்கள் என்ன செய்கிறோம் என்பதைப் பாருங்கள்',
    call: 'அழைக்கவும்',
    available: 'காலை 9 மணி முதல் மாலை 6 மணி வரை கிடைக்கும்',
    // SuperAdmin dashboard translations
    superAdminDashboard: 'சூப்பர் அட்மின் டாஷ்போர்டு',
    welcomeBack: 'மீண்டும் வரவேற்கிறோம்',
    userStatistics: 'பயனர் புள்ளிவிவரங்கள்',
    quickActions: 'விரைவு செயல்கள்',
    totalUsers: 'மொத்த பயனர்கள்',
    otherSuperAdmins: 'பிற சூப்பர் அட்மின்கள்',
    admins: 'அட்மின்கள்',
    regularUsers: 'வழக்கமான பயனர்கள்',
    activeUsers: 'செயலில் உள்ள பயனர்கள்',
    inactiveUsers: 'செயலற்ற பயனர்கள்',
    createNewAdmin: 'புதிய அட்மினை உருவாக்கு',
    manageUsers: 'பயனர்களை நிர்வகிக்கவும்',
    viewContacts: 'தொடர்புகளைக் காண்க',
    heroTitle: 'பாதுகாப்பான பின்னணி சரிபார்ப்பு எளிமையாக்கப்பட்டது',
    heroSubtitle: 'நம்பிக்கை, சரிபார்ப்பு மற்றும் நம்பிக்கையுடன் வேலைக்கு அமர்த்துங்கள்.',
    getStarted: 'தொடங்குங்கள்',
    learnMore: 'மேலும் அறியுங்கள்',
    welcomeBack: 'மீண்டும் வரவேற்கிறோம்',
    overview: 'கண்ணோட்டம்',
    userManagement: 'பயனர் மேலாண்மை',
    contactManagement: 'தொடர்பு மேலாண்மை',
    quickActions: 'விரைவு செயல்கள்',
    yourProfile: 'உங்கள் சுயவிவரம்',
    totalUsers: 'மொத்த பயனர்கள்',
    activeUsers: 'செயலில் உள்ள பயனர்கள்',
    inactiveUsers: 'செயலற்ற பயனர்கள்',
    createNewAdmin: 'புதிய நிர்வாகியை உருவாக்கு',
    manageUsers: 'பயனர்களை நிர்வகிக்கவும்',
    viewContacts: 'தொடர்புகளைக் காண்க',
    name: 'பெயர்',
    username: 'பயனர்பெயர்',
    role: 'பங்கு',
    status: 'நிலை',
    accountType: 'கணக்கு வகை',
    googleAccount: 'கூகிள் கணக்கு',
    regularAccount: 'வழக்கமான கணக்கு',
    searchUsers: 'பெயர், மின்னஞ்சல் அல்லது பயனர்பெயரால் தேடுங்கள்...',
    show: 'காட்டு',
    actions: 'செயல்கள்',
    activate: 'செயல்படுத்து',
    deactivate: 'செயலிழக்கச் செய்',
    delete: 'அழி',
    edit: 'திருத்து',
    view: 'காண்க',
    confirmDeletion: 'அழித்தலை உறுதிப்படுத்து',
    thisActionCannotBeUndone: 'இந்த செயலை மீளமுடியாது',
    deleteUser: 'பயனரை அழி',
    deleteAdmin: 'நிர்வாகியை அழி',
    deleteContact: 'தொடர்பை அழி',
    areYouSureDelete: 'நீங்கள் உறுதியாக அழிக்க விரும்புகிறீர்களா',
    cancel: 'ரத்து செய்',
    close: 'மூடு',
    loading: 'ஏற்றுகிறது...',
    next: 'அடுத்து',
    previous: 'முந்தைய',
    fullName: 'முழு பெயர்',
    email: 'மின்னஞ்சல்',
    phone: 'தொலைபேசி',
    message: 'செய்தி',
    sendMessage: 'செய்தியை அனுப்பு',
    contactInfo: 'தொடர்பு தகவல்',
    address: 'முகவரி',
    phoneNumber: 'தொலைபேசி எண்',
    contactTitle: 'எங்களை தொடர்பு கொள்ளுங்கள்',
    contactSubtitle: 'எந்தவொரு விசாரணைகளுக்கும் எங்களை தொடர்பு கொள்ளுங்கள்',
    aboutTitle: 'எங்களைப் பற்றி',
    aboutSubtitle: 'ஹைர்ஷீல்ட் என்பது பின்னணி சரிபார்ப்பு நிலப்பரப்பை புரட்சிகரமாக்கும் வேகமாக வளர்ந்து வரும் ஸ்டார்ட்அப் ஆகும்.',
    servicesTitle: 'எங்கள் சேவைகள்',
    servicesSubtitle: 'உங்கள் வணிக தேவைகளுக்கான விரிவான பின்னணி சரிபார்ப்பு தீர்வுகள்',
    criminalCheck: 'குற்றவியல் பின்னணி சரிபார்ப்பு',
    educationVerification: 'கல்வி சரிபார்ப்பு',
    employmentHistory: 'வேலை வரலாறு',
    addressVerification: 'முகவரி சரிபார்ப்பு',
    whyChooseUs: 'ஏன் எங்களைத் தேர்வு செய்ய வேண்டும்',
    fastVerification: 'விரைவு சரிபார்ப்பு',
    secureData: 'பாதுகாப்பான தரவு',
    comprehensiveChecks: 'விரிவான சரிபார்ப்புகள்',
    trustedBy: 'முன்னணி நிறுவனங்களால் நம்பப்படுகிறது',
    allRightsReserved: 'அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை',
    privacyPolicy: 'தனியுரிமைக் கொள்கை',
    termsOfService: 'சேவை விதிமுறைகள்',
    emailAddress: 'மின்னஞ்சல் முகவரி',
    password: 'கடவுச்சொல்',
    confirmPassword: 'கடவுச்சொல்லை உறுதிப்படுத்து',
    firstName: 'முதல் பெயர்',
    lastName: 'கடைசி பெயர்',
    forgotPassword: 'கடவுச்சொல்லை மறந்துவிட்டீர்களா?',
    dontHaveAccount: 'கணக்கு இல்லையா?',
    alreadyHaveAccount: 'ஏற்கனவே கணக்கு உள்ளதா?',
    signUp: 'பதிவு செய்க',
    signIn: 'உள்நுழைக',
    profileUpdated: 'சுயவிவரம் வெற்றிகரமாக புதுப்பிக்கப்பட்டது!',
    passwordChanged: 'கடவுச்சொல் வெற்றிகரமாக மாற்றப்பட்டது!',
    passwordsDoNotMatch: 'புதிய கடவுச்சொற்கள் பொருந்தவில்லை!',
    adminCreated: 'நிர்வாகி வெற்றிகரமாக உருவாக்கப்பட்டது!',
    userRoleUpdated: 'பயனர் பங்கு வெற்றிகரமாக புதுப்பிக்கப்பட்டது!',
    userStatusUpdated: 'பயனர் நிலை வெற்றிகரமாக புதுப்பிக்கப்பட்டது!',
    userDeleted: 'பயனர் வெற்றிகரமாக அழிக்கப்பட்டது!',
    contactDeleted: 'தொடர்பு சமர்ப்பிப்பு வெற்றிகரமாக அழிக்கப்பட்டது!',
    contactSubmitted: 'தொடர்பு படிவம் வெற்றிகரமாக சமர்ப்பிக்கப்பட்டது!',
    changePassword: 'கடவுச்சொல்லை மாற்று',
    updateProfile: 'சுயவிவரத்தை புதுப்பி',
    // HomePage additional translations
    secure: 'பாதுகாப்பான',
    compliant: 'இணக்கமான',
    verified: 'சரிபார்க்கப்பட்ட',
    trust: 'நம்பிக்கை',
    fast: 'விரைவான',
    reliable: 'நம்பகமான',
    precision: 'துல்லியம்',
    transparency: 'வெளிப்படைத்தன்மை',
    care: 'கவனிப்பு',
    verificationsCompleted: 'சரிபார்ப்புகள் முடிக்கப்பட்டன',
    uptimeAvailability: 'இயக்க நேரம் & கிடைப்பு',
    support: 'ஆதரவு',
    securityCompliance: 'பாதுகாப்பு & இணக்கம்',
    fastReliable: 'விரைவான & நம்பகமான',
    fastReliableDesc: 'நீங்கள் நம்பக்கூடிய துல்லியமான, தணிக்கை செய்யக்கூடிய முடிவுகளுடன் தொழில்துறை முன்னணி திருப்பம்.',
    compliantByDesign: 'வடிவமைப்பால் இணக்கமான',
    compliantByDesignDesc: 'தொழில்துறைகள் மற்றும் புவியியல்களில் பாதுகாப்பு மற்றும் ஒழுங்குமுறை சீரமைப்புக்காக கட்டமைக்கப்பட்டது.',
    scalesWithYou: 'உங்களுடன் அளவிடும்',
    scalesWithYouDesc: 'ஸ்டார்ட்அப்புகளிலிருந்து நிறுவனங்கள் வரை, உங்கள் பணிப்பாய்வுகளில் எளிதாக ஒருங்கிணைக்கவும்.',
    servicesDescription: 'வேலை வரலாறு மற்றும் கல்வி சரிபார்ப்புகளிலிருந்து குற்றவியல் பதிவுகள் மற்றும் அடையாள சரிபார்ப்பு வரை, உங்கள் தொழில்துறைக்கு தனிப்பயனாக்கப்பட்ட முழுமையான சேவைகளை நாங்கள் வழங்குகிறோம்.',
    employmentHistory: 'வேலை வரலாறு',
    educationChecks: 'கல்வி சரிபார்ப்புகள்',
    criminalRecords: 'குற்றவியல் பதிவுகள்',
    identityVerification: 'அடையாள சரிபார்ப்பு',
    addressVerification: 'முகவரி சரிபார்ப்பு',
    globalSanctions: 'உலகளாவிய தடைகள்',
    comprehensiveScreening: 'நவீன தரவு மூலங்கள் மற்றும் பாதுகாப்பான தானியங்கி மூலம் முழுமையான திரையிடல்.',
    learnMore: 'மேலும் அறியுங்கள் →',
    howItWorks: 'இது எப்படி வேலை செய்கிறது',
    initiate: '1. தொடங்கு',
    initiateDesc: 'ஒரு சரிபார்ப்பை உருவாக்கி வேட்பாளர்களை எங்கள் தளத்தின் மூலம் பாதுகாப்பாக அழைக்கவும்.',
    verify: '2. சரிபார்',
    verifyDesc: 'நாங்கள் நம்பகமான மூலங்களுடன் சரிபார்க்கிறோம் மற்றும் உங்களை நேரலை நேரத்தில் புதுப்பிக்கிறோம்.',
    decide: '3. முடிவு செய்',
    decideDesc: 'நம்பிக்கையான முடிவுகளை எடுக்க தெளிவான, இணக்கமான அறிக்கையைப் பெறுங்கள்.',
    buildSaferWorkplaces: 'பாதுகாப்பான பணியிடங்கள் மற்றும் வலுவான அணிகளை உருவாக்குங்கள்',
    oneVerifiedProfile: 'ஒரு சரிபார்க்கப்பட்ட சுயவிவரம் ஒரு நேரத்தில். நிமிடங்களில் உங்கள் அடுத்த சரிபார்ப்பைத் தொடங்குங்கள்.',
    getStarted: 'தொடங்குங்கள்',
    talkToUs: 'எங்களை தொடர்பு கொள்ளுங்கள்',
    // ContactPage additional translations
    haveQuestions: 'கேள்விகள் உள்ளனவா அல்லது உதவி தேவையா? உங்களிடமிருந்து கேட்க விரும்புகிறோம். எங்களுக்கு செய்தி அனுப்புங்கள், நாங்கள் விரைவில் பதிலளிப்போம்.',
    companyInformation: 'நிறுவன தகவல்',
    pleaseProvideCompany: 'உங்கள் நிறுவன விவரங்களை வழங்கவும் (விருப்பம்)',
    companyName: 'நிறுவன பெயர்',
    companyPhone: 'நிறுவன தொலைபேசி',
    companyEmail: 'நிறுவன மின்னஞ்சல்',
    companyAddress: 'நிறுவன முகவரி',
    enterCompanyName: 'உங்கள் நிறுவன பெயரை உள்ளிடவும்',
    enterCompanyPhone: 'நிறுவன தொலைபேசி எண்ணை உள்ளிடவும்',
    enterCompanyEmail: 'நிறுவன மின்னஞ்சல் முகவரியை உள்ளிடவும்',
    enterCompanyAddress: 'நிறுவன முகவரியை உள்ளிடவும்',
    businessHours: 'எங்கள் வணிக நேரங்கள்',
    mondayFriday: 'திங்கள் - வெள்ளி',
    saturday: 'சனி',
    sunday: 'ஞாயிறு',
    closed: 'மூடப்பட்டுள்ளது',
    emergencySupport: 'அவசர ஆதரவு:',
    available247: 'முக்கிய பிரச்சினைகளுக்கு 24/7 கிடைக்கும்',
    // LoginPage additional translations
    signInToAccount: 'உங்கள் கணக்கில் உள்நுழையுங்கள்',
    welcomeBackContinue: 'மீண்டும் வரவேற்கிறோம். தொடர உள்நுழையுங்கள்.',
    enterEmail: 'உங்கள் மின்னஞ்சலை உள்ளிடவும்',
    enterPassword: 'உங்கள் கடவுச்சொல்லை உள்ளிடவும்',
    orContinueWith: 'அல்லது தொடரவும்',
    continueWithGoogle: 'கூகிளுடன் தொடரவும்',
    dontHaveAccount: 'கணக்கு இல்லையா?',
    signUp: 'பதிவு செய்க',
    byContinuing: 'தொடர்வதன் மூலம், நீங்கள் எங்கள்',
    termsOfService: 'சேவை விதிமுறைகளை',
    and: 'மற்றும்',
    // SignupPage additional translations
    joinUs: 'எங்களுடன் சேருங்கள்',
    createAccountStarted: 'தொடங்க உங்கள் கணக்கை உருவாக்குங்கள்',
    createAccount: 'கணக்கை உருவாக்கு',
    step1Basic: 'படி 1: அடிப்படை தகவல்',
    step2Security: 'படி 2: பாதுகாப்பு அமைப்பு',
    username: 'பயனர்பெயர்',
    chooseUsername: 'பயனர்பெயரைத் தேர்ந்தெடுக்கவும்',
    firstName: 'முதல் பெயர்',
    lastName: 'கடைசி பெயர்',
    first_name: 'முதல் பெயர்',
    last_name: 'கடைசி பெயர்',
    continue: 'தொடரவும்',
    createStrongPassword: 'வலுவான கடவுச்சொல்லை உருவாக்கவும்',
    confirmPassword: 'கடவுச்சொல்லை உறுதிப்படுத்து',
    confirmYourPassword: 'உங்கள் கடவுச்சொல்லை உறுதிப்படுத்தவும்',
    creatingAccount: 'கணக்கு உருவாக்கப்படுகிறது...',
    processing: 'செயலாக்கப்படுகிறது...',
    signUpWithGoogle: 'கூகிளுடன் பதிவு செய்க',
    alreadyHaveAccount: 'ஏற்கனவே கணக்கு உள்ளதா?',
    signIn: 'உள்நுழையுங்கள்',
     // About page translations
    aboutDescription: 'ஹைர்ஷீல்ட் என்பது பின்னணி சரிபார்ப்பு நிலப்பரப்பை புரட்சிகரமாக்கும் வேகமாக வளர்ந்து வரும் ஸ்டார்ட்அப் ஆகும். 2025 இல் நிறுவப்பட்டு பெங்களூரில் தலைமையகம் கொண்ட ஹைர்ஷீல்ட், நவீன வணிகங்களுக்கான வேலைக்கு அமர்த்துதல் மற்றும் ஆன்போர்டிங் செயல்முறைகளில் நம்பிக்கை கட்டமைப்பதை எளிமையாக்கும் ஒரு பார்வையிலிருந்து பிறந்தது. தானியங்கி, AI-இயக்கப்பட்ட பகுப்பாய்வு மற்றும் மொபைல்-முதல் அணுகுமுறையை இணைப்பதன் மூலம், ஹைர்ஷீல்ட் ஸ்டார்ட்அப்புகள், SME கள் மற்றும் நிறுவன வாடிக்கையாளர்களுக்கு தனிப்பயனாக்கப்பட்ட வேகமான, நம்பகமான மற்றும் இணக்கமான சரிபார்ப்பு சேவைகளை வழங்குகிறது.',
    buildingTrustThroughInnovation: 'புதுமையின் மூலம் நம்பிக்கையை கட்டமைத்தல்',
    buildingTrustDescription: 'நிறுவனங்கள் தங்கள் மக்களை எவ்வாறு சரிபார்க்கிறார்கள் மற்றும் நம்புகிறார்கள் என்பதை மாற்றும் பணியில் நாங்கள் இருக்கிறோம், இந்த செயல்முறையை வேகமான, மிகவும் பாதுகாப்பான மற்றும் முற்றிலும் வெளிப்படையானதாக மாற்றுகிறோம்.',
    getStarted: 'தொடங்குங்கள்',
    ourServices: 'எங்கள் சேவைகள்',
    trustedByCompanies: '100+ நிறுவனங்களால் நம்பப்படுகிறது',
    mission: 'பணி',
    missionDescription: 'ஒவ்வொரு நிறுவனத்திற்கும் பின்னணி சரிபார்ப்பை இணைக்கும், வெளிப்படையான மற்றும் அணுகக்கூடியதாக மாற்றுவது — அளவு அல்லது தொழில்துறையைப் பொருட்படுத்தாமல்.',
    vision: 'பார்வை',
    visionDescription: 'டிஜிட்டல்-முதல் பொருளாதாரத்திற்கான மிகவும் விரைவான மற்றும் நம்பகமான பின்னணி சரிபார்ப்பு கூட்டாளியாக மாறுவது.',
    values: 'மதிப்புகள்',
    valuesDescription: 'தனியுரிமை, பாதுகாப்பு, வெளிப்படைத்தன்மை மற்றும் வாடிக்கையாளர் வெற்றி நாங்கள் செய்யும் அனைத்தையும் இயக்குகிறது.',
    whyChooseHiresheild: 'ஏன் ஹைர்ஷீல்டைத் தேர்வு செய்ய வேண்டும்?',
    fastEfficient: 'விரைவான & திறமையான',
    fastEfficientDesc: 'பாரம்பரிய முறைகளை விட 10 மடங்கு வேகமான AI-இயக்கப்பட்ட சரிபார்ப்பு',
    secureCompliant: 'பாதுகாப்பான & இணக்கமான',
    secureCompliantDesc: 'முழுமையான ஒழுங்குமுறை இணக்கத்துடன் நிறுவன-தர பாதுகாப்பு',
    mobileFirst: 'மொபைல்-முதல்',
    mobileFirstDesc: 'தொடர்ச்சியான மொபைல் அனுபவத்துடன் நவீன தொழிலாளர் சக்திக்காக கட்டமைக்கப்பட்டது',
    scalableSolution: 'அளவிடக்கூடிய தீர்வு',
    scalableSolutionDesc: 'ஸ்டார்ட்அப்பிலிருந்து நிறுவனம் வரை உங்கள் வணிகத்துடன் வளரும்',
    // Team page member bios
    kumarJagannathBio: 'குமார் என்பவர் உத்தி, செயல்பாடுகள் மற்றும் வாடிக்கையாளர் ஈடுபாட்டில் ஆண்டுகளின் அனுபவத்தைக் கொண்ட ஒரு மாறும் வணிகத் தலைவர். பகுப்பாய்வு மனநிலை மற்றும் ஒத்துழைப்பு தலைமைக்கு அறியப்பட்டவர், அவர் தகவல்தொடர்பு மற்றும் தொழில்நுட்ப ஸ்டார்ட்அப்புகள் மற்றும் டிஜிட்டல் மீடியா நிறுவனங்களை வழிநடத்தியுள்ளார். அவர் சிக்கலான பிரச்சினைகளை எளிய, அளவிடக்கூடிய தீர்வுகளுடன் தீர்க்கிறார் மற்றும் தொழில் மாற்றங்களை நடத்தும் தொழில்முறைவாதிகளுக்கு வழிகாட்டுதல் செய்கிறார்.',
    divyaMuruganBio: 'திவ்யா என்பவர் பிராண்ட் வளர்ச்சி, டிஜிட்டல் பிரச்சாரங்கள் மற்றும் நுகர்வோர் நுண்ணறிவுகளில் வலுவான பின்னணியைக் கொண்ட முடிவு-இயக்கப்பட்ட உத்தியாளர். படைப்பாற்றல் சிந்தனை மற்றும் தரவு-தகவலறிந்த முடிவுகளுக்கு அறியப்பட்டவர், அவர் வேகமான சூழல்களில் செழித்து வளர்கிறார் மற்றும் பார்வையாளர்களுடன் ஆழமாக இணைக்கும் கதைகளை உருவாக்குகிறார்.',
  },
  
  kn: {
    home: 'ಮುಖಪುಟ',
    about: 'ನಮ್ಮ ಬಗ್ಗೆ',
    services: 'ಸೇವೆಗಳು',
    team: 'ತಂಡ',
    contact: 'ಸಂಪರ್ಕ',
    login: 'ಲಾಗಿನ್',
    signup: 'ಸೈನ್ ಅಪ್',
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    logout: 'ಲಾಗ್‌ಔಟ್',
    getVerified: 'ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
    language: 'ಭಾಷೆ',
    // Team page translations
    ourTeam: 'ನಮ್ಮ ತಂಡ',
    peopleBehindMission: 'ಮಿಷನ್ ಹಿಂದೆ ಇರುವ ಜನರು — ನಂಬಲರ್ಹ, ಅನುಸರಣೆ ಮತ್ತು ಮಾಪನೀಯ ಪರಿಶೀಲನೆ ಅನುಭವಗಳನ್ನು ನಿರ್ಮಿಸುತ್ತಿದ್ದಾರೆ.',
    weBuildWithTrust: 'ನಾವು ನಂಬಿಕೆಯೊಂದಿಗೆ ನಿರ್ಮಿಸುತ್ತೇವೆ',
    teamBlendsStrategy: 'ನಮ್ಮ ತಂಡವು ತಂತ್ರ, ಸೃಜನಶೀಲತೆ ಮತ್ತು ತಂತ್ರಜ್ಞಾನವನ್ನು ಸಂಯೋಜಿಸಿ ವೇಗವಾದ, ಅನುಸರಣೆ ಮತ್ತು ಮಾನವ-ಕೇಂದ್ರಿತ ಪರಿಶೀಲನೆ ಅನುಭವಗಳನ್ನು ನೀಡುತ್ತದೆ.',
    workWithUs: 'ನಮ್ಮೊಂದಿಗೆ ಕೆಲಸ ಮಾಡಿ',
    seeWhatWeDo: 'ನಾವು ಏನು ಮಾಡುತ್ತೇವೆ ಎಂದು ನೋಡಿ',
    call: 'ಕರೆ ಮಾಡಿ',
    available: 'ಬೆಳಗಿನ 9 ರಿಂದ ಸಂಜೆ 6 ರವರೆಗೆ ಲಭ್ಯವಿದೆ',
    // SuperAdmin dashboard translations
    superAdminDashboard: 'ಸೂಪರ್ ಅಡ್ಮಿನ್ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    welcomeBack: 'ಮತ್ತೆ ಸ್ವಾಗತ',
    userStatistics: 'ಬಳಕೆದಾರರ ಅಂಕಿಅಂಶಗಳು',
    quickActions: 'ತ್ವರಿತ ಕ್ರಿಯೆಗಳು',
    totalUsers: 'ಒಟ್ಟು ಬಳಕೆದಾರರು',
    otherSuperAdmins: 'ಇತರ ಸೂಪರ್ ಅಡ್ಮಿನ್‌ಗಳು',
    admins: 'ಅಡ್ಮಿನ್‌ಗಳು',
    regularUsers: 'ಸಾಮಾನ್ಯ ಬಳಕೆದಾರರು',
    activeUsers: 'ಸಕ್ರಿಯ ಬಳಕೆದಾರರು',
    inactiveUsers: 'ನಿಷ್ಕ್ರಿಯ ಬಳಕೆದಾರರು',
    createNewAdmin: 'ಹೊಸ ಅಡ್ಮಿನ್ ರಚಿಸಿ',
    manageUsers: 'ಬಳಕೆದಾರರನ್ನು ನಿರ್ವಹಿಸಿ',
    viewContacts: 'ಸಂಪರ್ಕಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
    heroTitle: 'ಸುರಕ್ಷಿತ ಹಿನ್ನೆಲೆ ಪರಿಶೀಲನೆ ಸರಳಗೊಳಿಸಲಾಗಿದೆ',
    heroSubtitle: 'ನಂಬಿಕೆ, ಪರಿಶೀಲಿಸಿ ಮತ್ತು ವಿಶ್ವಾಸದಿಂದ ನೇಮಕ ಮಾಡಿ.',
    getStarted: 'ಪ್ರಾರಂಭಿಸಿ',
    learnMore: 'ಹೆಚ್ಚು ತಿಳಿಯಿರಿ',
    welcomeBack: 'ಮತ್ತೆ ಸ್ವಾಗತ',
    overview: 'ಅವಲೋಕನ',
    userManagement: 'ಬಳಕೆದಾರ ನಿರ್ವಹಣೆ',
    contactManagement: 'ಸಂಪರ್ಕ ನಿರ್ವಹಣೆ',
    quickActions: 'ತ್ವರಿತ ಕ್ರಿಯೆಗಳು',
    yourProfile: 'ನಿಮ್ಮ ಪ್ರೊಫೈಲ್',
    totalUsers: 'ಒಟ್ಟು ಬಳಕೆದಾರರು',
    activeUsers: 'ಸಕ್ರಿಯ ಬಳಕೆದಾರರು',
    inactiveUsers: 'ನಿಷ್ಕ್ರಿಯ ಬಳಕೆದಾರರು',
    createNewAdmin: 'ಹೊಸ ನಿರ್ವಾಹಕ ರಚಿಸಿ',
    manageUsers: 'ಬಳಕೆದಾರರನ್ನು ನಿರ್ವಹಿಸಿ',
    viewContacts: 'ಸಂಪರ್ಕಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
    name: 'ಹೆಸರು',
    username: 'ಬಳಕೆದಾರ ಹೆಸರು',
    role: 'ಪಾತ್ರ',
    status: 'ಸ್ಥಿತಿ',
    accountType: 'ಖಾತೆ ಪ್ರಕಾರ',
    googleAccount: 'ಗೂಗಲ್ ಖಾತೆ',
    regularAccount: 'ಸಾಮಾನ್ಯ ಖಾತೆ',
    searchUsers: 'ಹೆಸರು, ಇಮೇಲ್ ಅಥವಾ ಬಳಕೆದಾರ ಹೆಸರಿನಿಂದ ಹುಡುಕಿ...',
    show: 'ತೋರಿಸು',
    actions: 'ಕ್ರಿಯೆಗಳು',
    activate: 'ಸಕ್ರಿಯಗೊಳಿಸು',
    deactivate: 'ನಿಷ್ಕ್ರಿಯಗೊಳಿಸು',
    delete: 'ಅಳಿಸಿ',
    edit: 'ಸಂಪಾದಿಸಿ',
    view: 'ವೀಕ್ಷಿಸಿ',
    confirmDeletion: 'ಅಳಿಸುವಿಕೆಯನ್ನು ದೃಢೀಕರಿಸಿ',
    thisActionCannotBeUndone: 'ಈ ಕ್ರಿಯೆಯನ್ನು ರದ್ದುಮಾಡಲಾಗುವುದಿಲ್ಲ',
    deleteUser: 'ಬಳಕೆದಾರರನ್ನು ಅಳಿಸಿ',
    deleteAdmin: 'ನಿರ್ವಾಹಕರನ್ನು ಅಳಿಸಿ',
    deleteContact: 'ಸಂಪರ್ಕವನ್ನು ಅಳಿಸಿ',
    areYouSureDelete: 'ನೀವು ಖಚಿತವಾಗಿ ಅಳಿಸಲು ಬಯಸುವಿರಾ',
    cancel: 'ರದ್ದುಮಾಡಿ',
    close: 'ಮುಚ್ಚಿ',
    loading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    next: 'ಮುಂದೆ',
    previous: 'ಹಿಂದೆ',
    fullName: 'ಪೂರ್ಣ ಹೆಸರು',
    email: 'ಇಮೇಲ್',
    phone: 'ಫೋನ್',
    message: 'ಸಂದೇಶ',
    sendMessage: 'ಸಂದೇಶ ಕಳುಹಿಸಿ',
    contactInfo: 'ಸಂಪರ್ಕ ಮಾಹಿತಿ',
    address: 'ವಿಳಾಸ',
    phoneNumber: 'ಫೋನ್ ಸಂಖ್ಯೆ',
    contactTitle: 'ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ',
    contactSubtitle: 'ಯಾವುದೇ ಪ್ರಶ್ನೆಗಳಿಗಾಗಿ ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ',
    aboutTitle: 'ನಮ್ಮ ಬಗ್ಗೆ',
    aboutSubtitle: 'ಹೈರ್‌ಶೀಲ್ಡ್ ಎಂಬುದು ಹಿನ್ನೆಲೆ ಪರಿಶೀಲನೆ ಭೂದೃಶ್ಯವನ್ನು ಕ್ರಾಂತಿಕಾರಕವಾಗಿ ಬದಲಾಯಿಸುತ್ತಿರುವ ವೇಗವಾಗಿ ಬೆಳೆಯುತ್ತಿರುವ ಸ್ಟಾರ್ಟ್‌ಅಪ್ ಆಗಿದೆ.',
    servicesTitle: 'ನಮ್ಮ ಸೇವೆಗಳು',
    servicesSubtitle: 'ನಿಮ್ಮ ವ್ಯವಹಾರದ ಅಗತ್ಯತೆಗಳಿಗಾಗಿ ಸಮಗ್ರ ಹಿನ್ನೆಲೆ ಪರಿಶೀಲನೆ ಪರಿಹಾರಗಳು',
    criminalCheck: 'ಕ್ರಿಮಿನಲ್ ಹಿನ್ನೆಲೆ ಪರಿಶೀಲನೆ',
    educationVerification: 'ಶಿಕ್ಷಣ ಪರಿಶೀಲನೆ',
    employmentHistory: 'ಉದ್ಯೋಗ ಇತಿಹಾಸ',
    addressVerification: 'ವಿಳಾಸ ಪರಿಶೀಲನೆ',
    whyChooseUs: 'ಏಕೆ ನಮ್ಮನ್ನು ಆಯ್ಕೆ ಮಾಡಬೇಕು',
    fastVerification: 'ವೇಗದ ಪರಿಶೀಲನೆ',
    secureData: 'ಸುರಕ್ಷಿತ ಡೇಟಾ',
    comprehensiveChecks: 'ಸಮಗ್ರ ಪರಿಶೀಲನೆಗಳು',
    trustedBy: 'ಪ್ರಮುಖ ಕಂಪನಿಗಳಿಂದ ನಂಬಲ್ಪಟ್ಟಿದೆ',
    allRightsReserved: 'ಎಲ್ಲ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದುಕೊಳ್ಳಲಾಗಿದೆ',
    privacyPolicy: 'ಗೌಪ್ಯತೆ ನೀತಿ',
    termsOfService: 'ಸೇವೆಯ ನಿಯಮಗಳು',
    emailAddress: 'ಇಮೇಲ್ ವಿಳಾಸ',
    password: 'ಪಾಸ್‌ವರ್ಡ್',
    confirmPassword: 'ಪಾಸ್‌ವರ್ಡ್ ದೃಢೀಕರಿಸಿ',
    firstName: 'ಮೊದಲ ಹೆಸರು',
    lastName: 'ಕೊನೆಯ ಹೆಸರು',
    forgotPassword: 'ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿರುವಿರಾ?',
    dontHaveAccount: 'ಖಾತೆ ಇಲ್ಲವೇ?',
    alreadyHaveAccount: 'ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ?',
    signUp: 'ಸೈನ್ ಅಪ್',
    signIn: 'ಸೈನ್ ಇನ್',
    profileUpdated: 'ಪ್ರೊಫೈಲ್ ಯಶಸ್ವಿಯಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ!',
    passwordChanged: 'ಪಾಸ್‌ವರ್ಡ್ ಯಶಸ್ವಿಯಾಗಿ ಬದಲಾಯಿಸಲಾಗಿದೆ!',
    passwordsDoNotMatch: 'ಹೊಸ ಪಾಸ್‌ವರ್ಡ್‌ಗಳು ಹೊಂದಾಣಿಕೆಯಾಗುತ್ತಿಲ್ಲ!',
    adminCreated: 'ನಿರ್ವಾಹಕ ಯಶಸ್ವಿಯಾಗಿ ರಚಿಸಲಾಗಿದೆ!',
    userRoleUpdated: 'ಬಳಕೆದಾರ ಪಾತ್ರ ಯಶಸ್ವಿಯಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ!',
    userStatusUpdated: 'ಬಳಕೆದಾರ ಸ್ಥಿತಿ ಯಶಸ್ವಿಯಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ!',
    userDeleted: 'ಬಳಕೆದಾರ ಯಶಸ್ವಿಯಾಗಿ ಅಳಿಸಲಾಗಿದೆ!',
    contactDeleted: 'ಸಂಪರ್ಕ ಸಲ್ಲಿಕೆ ಯಶಸ್ವಿಯಾಗಿ ಅಳಿಸಲಾಗಿದೆ!',
    contactSubmitted: 'ಸಂಪರ್ಕ ಫಾರ್ಮ್ ಯಶಸ್ವಿಯಾಗಿ ಸಲ್ಲಿಸಲಾಗಿದೆ!',
    changePassword: 'ಪಾಸ್‌ವರ್ಡ್ ಬದಲಾಯಿಸಿ',
    updateProfile: 'ಪ್ರೊಫೈಲ್ ನವೀಕರಿಸಿ',
    // HomePage additional translations
    secure: 'ಸುರಕ್ಷಿತ',
    compliant: 'ಅನುಸರಣೆ',
    verified: 'ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
    trust: 'ನಂಬಿಕೆ',
    fast: 'ವೇಗದ',
    reliable: 'ವಿಶ್ವಾಸಾರ್ಹ',
    precision: 'ನಿಖರತೆ',
    transparency: 'ಪಾರದರ್ಶಕತೆ',
    care: 'ಕಾಳಜಿ',
    verificationsCompleted: 'ಪರಿಶೀಲನೆಗಳು ಪೂರ್ಣಗೊಂಡಿವೆ',
    uptimeAvailability: 'ಅಪ್‌ಟೈಮ್ & ಲಭ್ಯತೆ',
    support: 'ಬೆಂಬಲ',
    securityCompliance: 'ಸುರಕ್ಷತೆ & ಅನುಸರಣೆ',
    fastReliable: 'ವೇಗದ & ವಿಶ್ವಾಸಾರ್ಹ',
    fastReliableDesc: 'ನೀವು ನಂಬಬಹುದಾದ ನಿಖರ, ಆಡಿಟ್ ಮಾಡಬಹುದಾದ ಫಲಿತಾಂಶಗಳೊಂದಿಗೆ ಉದ್ಯಮದ ಮುಂಚೂಣಿ ತಿರುಗುವಿಕೆ.',
    compliantByDesign: 'ವಿನ್ಯಾಸದಿಂದ ಅನುಸರಣೆ',
    compliantByDesignDesc: 'ಉದ್ಯಮಗಳು ಮತ್ತು ಭೌಗೋಳಿಕ ಪ್ರದೇಶಗಳಲ್ಲಿ ಸುರಕ್ಷತೆ ಮತ್ತು ನಿಯಂತ್ರಣ ಜೋಡಣೆಗಾಗಿ ನಿರ್ಮಿಸಲಾಗಿದೆ.',
    scalesWithYou: 'ನಿಮ್ಮೊಂದಿಗೆ ಪ್ರಮಾಣಗಳು',
    scalesWithYouDesc: 'ಸ್ಟಾರ್ಟ್‌ಅಪ್‌ಗಳಿಂದ ಎಂಟರ್ಪ್ರೈಸ್‌ಗಳವರೆಗೆ, ನಿಮ್ಮ ವರ್ಕ್‌ಫ್ಲೋಗಳಲ್ಲಿ ಸುಲಭವಾಗಿ ಸಂಯೋಜಿಸಿ.',
    servicesDescription: 'ಉದ್ಯೋಗ ಇತಿಹಾಸ ಮತ್ತು ಶಿಕ್ಷಣ ಪರಿಶೀಲನೆಗಳಿಂದ ಕ್ರಿಮಿನಲ್ ದಾಖಲೆಗಳು ಮತ್ತು ಗುರುತಿನ ಪರಿಶೀಲನೆಗೆ, ನಿಮ್ಮ ಉದ್ಯಮಕ್ಕೆ ಹೊಂದಾಣಿಕೆಯಾದ ಸಂಪೂರ್ಣ ಸೇವೆಗಳನ್ನು ನಾವು ನೀಡುತ್ತೇವೆ.',
    employmentHistory: 'ಉದ್ಯೋಗ ಇತಿಹಾಸ',
    educationChecks: 'ಶಿಕ್ಷಣ ಪರಿಶೀಲನೆಗಳು',
    criminalRecords: 'ಕ್ರಿಮಿನಲ್ ದಾಖಲೆಗಳು',
    identityVerification: 'ಗುರುತಿನ ಪರಿಶೀಲನೆ',
    addressVerification: 'ವಿಳಾಸ ಪರಿಶೀಲನೆ',
    globalSanctions: 'ಜಾಗತಿಕ ನಿರ್ಬಂಧಗಳು',
    comprehensiveScreening: 'ಆಧುನಿಕ ಡೇಟಾ ಮೂಲಗಳು ಮತ್ತು ಸುರಕ್ಷಿತ ಸ್ವಯಂಚಾಲನೆಯಿಂದ ಸಮಗ್ರ ತಪಾಸಣೆ.',
    learnMore: 'ಹೆಚ್ಚು ತಿಳಿಯಿರಿ →',
    howItWorks: 'ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ',
    initiate: '1. ಪ್ರಾರಂಭಿಸಿ',
    initiateDesc: 'ಪರಿಶೀಲನೆಯನ್ನು ರಚಿಸಿ ಮತ್ತು ಅಭ್ಯರ್ಥಿಗಳನ್ನು ನಮ್ಮ ವೇದಿಕೆಯ ಮೂಲಕ ಸುರಕ್ಷಿತವಾಗಿ ಆಹ್ವಾನಿಸಿ.',
    verify: '2. ಪರಿಶೀಲಿಸಿ',
    verifyDesc: 'ನಾವು ವಿಶ್ವಾಸಾರ್ಹ ಮೂಲಗಳೊಂದಿಗೆ ಪರಿಶೀಲಿಸುತ್ತೇವೆ ಮತ್ತು ನಿಮ್ಮನ್ನು ನೈಜ ಸಮಯದಲ್ಲಿ ನವೀಕರಿಸುತ್ತೇವೆ.',
    decide: '3. ನಿರ್ಧರಿಸಿ',
    decideDesc: 'ವಿಶ್ವಾಸಾರ್ಹ ನಿರ್ಧಾರಗಳನ್ನು ತೆಗೆದುಕೊಳ್ಳಲು ಸ್ಪಷ್ಟ, ಅನುಸರಣೆಯ ವರದಿಯನ್ನು ಸ್ವೀಕರಿಸಿ.',
    buildSaferWorkplaces: 'ಸುರಕ್ಷಿತ ಕೆಲಸದ ಸ್ಥಳಗಳು ಮತ್ತು ಬಲವಾದ ತಂಡಗಳನ್ನು ನಿರ್ಮಿಸಿ',
    oneVerifiedProfile: 'ಒಂದು ಪರಿಶೀಲಿಸಲಾದ ಪ್ರೊಫೈಲ್ ಒಂದು ಸಮಯದಲ್ಲಿ. ನಿಮ್ಮ ಮುಂದಿನ ಪರಿಶೀಲನೆಯನ್ನು ನಿಮಿಷಗಳಲ್ಲಿ ಪ್ರಾರಂಭಿಸಿ.',
    getStarted: 'ಪ್ರಾರಂಭಿಸಿ',
    talkToUs: 'ನಮ್ಮೊಂದಿಗೆ ಮಾತನಾಡಿ',
    // ContactPage additional translations
    haveQuestions: 'ಪ್ರಶ್ನೆಗಳಿವೆಯೇ ಅಥವಾ ಸಹಾಯ ಬೇಕೇ? ನಿಮ್ಮಿಂದ ಕೇಳಲು ನಮಗೆ ಇಷ್ಟವಿದೆ. ನಮಗೆ ಸಂದೇಶ ಕಳುಹಿಸಿ ಮತ್ತು ನಾವು ತಕ್ಷಣವೇ ಪ್ರತಿಕ್ರಿಯಿಸುತ್ತೇವೆ.',
    companyInformation: 'ಕಂಪನಿ ಮಾಹಿತಿ',
    pleaseProvideCompany: 'ದಯವಿಟ್ಟು ನಿಮ್ಮ ಕಂಪನಿ ವಿವರಗಳನ್ನು ಒದಗಿಸಿ (ಐಚ್ಛಿಕ)',
    companyName: 'ಕಂಪನಿ ಹೆಸರು',
    companyPhone: 'ಕಂಪನಿ ಫೋನ್',
    companyEmail: 'ಕಂಪನಿ ಇಮೇಲ್',
    companyAddress: 'ಕಂಪನಿ ವಿಳಾಸ',
    enterCompanyName: 'ನಿಮ್ಮ ಕಂಪನಿ ಹೆಸರನ್ನು ನಮೂದಿಸಿ',
    enterCompanyPhone: 'ಕಂಪನಿ ಫೋನ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ',
    enterCompanyEmail: 'ಕಂಪನಿ ಇಮೇಲ್ ವಿಳಾಸವನ್ನು ನಮೂದಿಸಿ',
    enterCompanyAddress: 'ಕಂಪನಿ ವಿಳಾಸವನ್ನು ನಮೂದಿಸಿ',
    businessHours: 'ನಮ್ಮ ವ್ಯಾಪಾರದ ಗಂಟೆಗಳು',
    mondayFriday: 'ಸೋಮವಾರ - ಶುಕ್ರವಾರ',
    saturday: 'ಶನಿವಾರ',
    sunday: 'ಭಾನುವಾರ',
    closed: 'ಮುಚ್ಚಲಾಗಿದೆ',
    emergencySupport: 'ತುರ್ತು ಬೆಂಬಲ:',
    available247: 'ವಿಮರ್ಶಾತ್ಮಕ ಸಮಸ್ಯೆಗಳಿಗಾಗಿ 24/7 ಲಭ್ಯವಿದೆ',
    // LoginPage additional translations
    signInToAccount: 'ನಿಮ್ಮ ಖಾತೆಗೆ ಸೈನ್ ಇನ್ ಮಾಡಿ',
    welcomeBackContinue: 'ಮತ್ತೆ ಸ್ವಾಗತ. ಮುಂದುವರಿಸಲು ದಯವಿಟ್ಟು ಸೈನ್ ಇನ್ ಮಾಡಿ.',
    enterEmail: 'ನಿಮ್ಮ ಇಮೇಲ್ ನಮೂದಿಸಿ',
    enterPassword: 'ನಿಮ್ಮ ಪಾಸ್‌ವರ್ಡ್ ನಮೂದಿಸಿ',
    orContinueWith: 'ಅಥವಾ ಮುಂದುವರಿಸಿ',
    continueWithGoogle: 'ಗೂಗಲ್‌ನೊಂದಿಗೆ ಮುಂದುವರಿಸಿ',
    dontHaveAccount: 'ಖಾತೆ ಇಲ್ಲವೇ?',
    signUp: 'ಸೈನ್ ಅಪ್',
    byContinuing: 'ಮುಂದುವರಿಸುವ ಮೂಲಕ, ನೀವು ನಮ್ಮ',
    termsOfService: 'ಸೇವೆಯ ನಿಯಮಗಳನ್ನು',
    and: 'ಮತ್ತು',
    // SignupPage additional translations
    joinUs: 'ನಮ್ಮೊಂದಿಗೆ ಸೇರಿ',
    createAccountStarted: 'ಪ್ರಾರಂಭಿಸಲು ನಿಮ್ಮ ಖಾತೆಯನ್ನು ರಚಿಸಿ',
    createAccount: 'ಖಾತೆ ರಚಿಸಿ',
    step1Basic: 'ಹಂತ 1: ಮೂಲ ಮಾಹಿತಿ',
    step2Security: 'ಹಂತ 2: ಸುರಕ್ಷತೆ ಸೆಟಪ್',
    username: 'ಬಳಕೆದಾರ ಹೆಸರು',
    chooseUsername: 'ಬಳಕೆದಾರ ಹೆಸರನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    firstName: 'ಮೊದಲ ಹೆಸರು',
    lastName: 'ಕೊನೆಯ ಹೆಸರು',
    first_name: 'ಮೊದಲ ಹೆಸರು',
    last_name: 'ಕೊನೆಯ ಹೆಸರು',
    continue: 'ಮುಂದುವರಿಸಿ',
    createStrongPassword: 'ಬಲವಾದ ಪಾಸ್‌ವರ್ಡ್ ರಚಿಸಿ',
    confirmPassword: 'ಪಾಸ್‌ವರ್ಡ್ ದೃಢೀಕರಿಸಿ',
    confirmYourPassword: 'ನಿಮ್ಮ ಪಾಸ್‌ವರ್ಡ್ ದೃಢೀಕರಿಸಿ',
    creatingAccount: 'ಖಾತೆ ರಚಿಸಲಾಗುತ್ತಿದೆ...',
    processing: 'ಸಂಸ್ಕರಿಸಲಾಗುತ್ತಿದೆ...',
    signUpWithGoogle: 'ಗೂಗಲ್‌ನೊಂದಿಗೆ ಸೈನ್ ಅಪ್ ಮಾಡಿ',
    alreadyHaveAccount: 'ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ?',
    signIn: 'ಸೈನ್ ಇನ್',
     // About page translations
    aboutDescription: 'ಹೈರ್‌ಶೀಲ್ಡ್ ಎಂಬುದು ಹಿನ್ನೆಲೆ ಪರಿಶೀಲನೆ ಭೂದೃಶ್ಯವನ್ನು ಕ್ರಾಂತಿಕಾರಕವಾಗಿ ಬದಲಾಯಿಸುತ್ತಿರುವ ವೇಗವಾಗಿ ಬೆಳೆಯುತ್ತಿರುವ ಸ್ಟಾರ್ಟ್‌ಅಪ್ ಆಗಿದೆ. 2025 ರಲ್ಲಿ ಸ್ಥಾಪಿಸಲ್ಪಟ್ಟು ಬೆಂಗಳೂರಿನಲ್ಲಿ ಪ್ರಧಾನ ಕಛೇರಿಯನ್ನು ಹೊಂದಿರುವ ಹೈರ್‌ಶೀಲ್ಡ್, ಆಧುನಿಕ ವ್ಯವಹಾರಗಳಿಗೆ ನೇಮಕಾತಿ ಮತ್ತು ಆನ್‌ಬೋರ್ಡಿಂಗ್ ಪ್ರಕ್ರಿಯೆಗಳಲ್ಲಿ ನಂಬಿಕೆ ನಿರ್ಮಿಸುವುದನ್ನು ಸರಳಗೊಳಿಸುವ ದೃಷ್ಟಿಯಿಂದ ಹುಟ್ಟಿಕೊಂಡಿದೆ. ಸ್ವಯಂಚಾಲನೆ, AI-ಚಾಲಿತ ವಿಶ್ಲೇಷಣೆ ಮತ್ತು ಮೊಬೈಲ್-ಮೊದಲ ವಿಧಾನವನ್ನು ಸಂಯೋಜಿಸುವ ಮೂಲಕ, ಹೈರ್‌ಶೀಲ್ಡ್ ಸ್ಟಾರ್ಟ್‌ಅಪ್‌ಗಳು, SME ಗಳು ಮತ್ತು ಉದ್ಯಮ ಗ್ರಾಹಕರಿಗೆ ಹೊಂದಾಣಿಕೆಯಾದ ವೇಗವಾದ, ವಿಶ್ವಾಸಾರ್ಹ ಮತ್ತು ಅನುಸರಣೆಯ ಪರಿಶೀಲನೆ ಸೇವೆಗಳನ್ನು ನೀಡುತ್ತದೆ.',
    buildingTrustThroughInnovation: 'ನಾವೀನ್ಯತೆಯ ಮೂಲಕ ನಂಬಿಕೆ ನಿರ್ಮಿಸುವುದು',
    buildingTrustDescription: 'ಸಂಸ್ಥೆಗಳು ತಮ್ಮ ಜನರನ್ನು ಹೇಗೆ ಪರಿಶೀಲಿಸುತ್ತವೆ ಮತ್ತು ನಂಬುತ್ತವೆ ಎಂಬುದನ್ನು ರೂಪಾಂತರಿಸುವ ಮಿಷನ್‌ನಲ್ಲಿ ನಾವು ಇದ್ದೇವೆ, ಈ ಪ್ರಕ್ರಿಯೆಯನ್ನು ವೇಗವಾಗಿ, ಹೆಚ್ಚು ಸುರಕ್ಷಿತ ಮತ್ತು ಸಂಪೂರ್ಣವಾಗಿ ಪಾರದರ್ಶಕವಾಗಿ ಮಾಡುತ್ತೇವೆ.',
    getStarted: 'ಪ್ರಾರಂಭಿಸಿ',
    ourServices: 'ನಮ್ಮ ಸೇವೆಗಳು',
    trustedByCompanies: '100+ ಕಂಪನಿಗಳಿಂದ ನಂಬಲ್ಪಟ್ಟಿದೆ',
    mission: 'ಮಿಷನ್',
    missionDescription: 'ಪ್ರತಿ ಸಂಸ್ಥೆಗೆ ಹಿನ್ನೆಲೆ ಪರಿಶೀಲನೆಯನ್ನು ನಿರಾತಂಕ, ಪಾರದರ್ಶಕ ಮತ್ತು ಪ್ರವೇಶಿಸಬಹುದಾಗಿ ಮಾಡುವುದು — ಗಾತ್ರ ಅಥವಾ ಉದ್ಯಮವನ್ನು ಲೆಕ್ಕಿಸದೆ.',
    vision: 'ದೃಷ್ಟಿ',
    visionDescription: 'ಡಿಜಿಟಲ್-ಮೊದಲ ಆರ್ಥಿಕತೆಗೆ ಅತ್ಯಂತ ಚುರುಕಾದ ಮತ್ತು ನಂಬಲರ್ಹ ಹಿನ್ನೆಲೆ ಪರಿಶೀಲನೆ ಪಾಲುದಾರರಾಗುವುದು.',
    values: 'ಮೌಲ್ಯಗಳು',
    valuesDescription: 'ಗೌಪ್ಯತೆ, ಸುರಕ್ಷತೆ, ಪಾರದರ್ಶಕತೆ ಮತ್ತು ಗ್ರಾಹಕ ಯಶಸ್ಸು ನಾವು ಮಾಡುವ ಎಲ್ಲವನ್ನೂ ಚಾಲನೆ ಮಾಡುತ್ತದೆ.',
    whyChooseHiresheild: 'ಏಕೆ ಹೈರ್‌ಶೀಲ್ಡ್ ಅನ್ನು ಆಯ್ಕೆ ಮಾಡಬೇಕು?',
    fastEfficient: 'ವೇಗದ & ಸಮರ್ಥ',
    fastEfficientDesc: 'ಸಾಂಪ್ರದಾಯಿಕ ವಿಧಾನಗಳಿಗಿಂತ 10 ಪಟ್ಟು ವೇಗವಾದ AI-ಚಾಲಿತ ಪರಿಶೀಲನೆ',
    secureCompliant: 'ಸುರಕ್ಷಿತ & ಅನುಸರಣೆ',
    secureCompliantDesc: 'ಸಂಪೂರ್ಣ ನಿಯಂತ್ರಣ ಅನುಸರಣೆಯೊಂದಿಗೆ ಉದ್ಯಮ-ದರ್ಜೆಯ ಸುರಕ್ಷತೆ',
    mobileFirst: 'ಮೊಬೈಲ್-ಮೊದಲ',
    mobileFirstDesc: 'ನಿರಂತರ ಮೊಬೈಲ್ ಅನುಭವದೊಂದಿಗೆ ಆಧುನಿಕ ಕಾರ್ಯಪಡೆಗಾಗಿ ನಿರ್ಮಿಸಲಾಗಿದೆ',
    scalableSolution: 'ಮಾಪನೀಯ ಪರಿಹಾರ',
    scalableSolutionDesc: 'ಸ್ಟಾರ್ಟ್‌ಅಪ್‌ಗಳಿಂದ ಉದ್ಯಮಗಳವರೆಗೆ ನಿಮ್ಮ ವ್ಯವಹಾರದೊಂದಿಗೆ ಬೆಳೆಯುತ್ತದೆ',
    // Team page member bios
    kumarJagannathBio: 'ಕುಮಾರ್ ಎಂಬುವವರು ತಂತ್ರ, ಕಾರ್ಯಾಚರಣೆ ಮತ್ತು ಗ್ರಾಹಕ ತೊಡಗಿಸಿಕೊಳ್ಳುವಿಕೆಯಲ್ಲಿ ವರ್ಷಗಳ ಅನುಭವವನ್ನು ಹೊಂದಿರುವ ಚಲನಶೀಲ ವ್ಯವಹಾರ ನಾಯಕ. ವಿಶ್ಲೇಷಣಾತ್ಮಕ ಮನಸ್ಥಿತಿ ಮತ್ತು ಸಹಕಾರಿ ನಾಯಕತ್ವಕ್ಕೆ ಹೆಸರುವಾಸಿಯಾದವರು, ಅವರು ಸಂವಹನ ಮತ್ತು ತಂತ್ರಜ್ಞಾನ ಸ್ಟಾರ್ಟ್‌ಅಪ್‌ಗಳು ಮತ್ತು ಡಿಜಿಟಲ್ ಮೀಡಿಯಾ ಕಂಪನಿಗಳನ್ನು ನಡೆಸಿದ್ದಾರೆ. ಅವರು ಸರಳ, ಮಾಪನೀಯ ಪರಿಹಾರಗಳೊಂದಿಗೆ ಸಂಕೀರ್ಣ ಸಮಸ್ಯೆಗಳನ್ನು ಪರಿಹರಿಸುತ್ತಾರೆ ಮತ್ತು ವೃತ್ತಿಜೀವನ ಪರಿವರ್ತನೆಗಳನ್ನು ನಿರ್ವಹಿಸುವ ವೃತ್ತಿಪರರಿಗೆ ಮಾರ್ಗದರ್ಶನ ನೀಡುತ್ತಾರೆ.',
    divyaMuruganBio: 'ದಿವ್ಯಾ ಎಂಬುವವರು ಬ್ರಾಂಡ್ ಅಭಿವೃದ್ಧಿ, ಡಿಜಿಟಲ್ ಪ್ರಚಾರಗಳು ಮತ್ತು ಗ್ರಾಹಕ ಒಳನೋಟಗಳಲ್ಲಿ ಬಲವಾದ ಹಿನ್ನೆಲೆಯನ್ನು ಹೊಂದಿರುವ ಫಲಿತಾಂಶ-ಚಾಲಿತ ತಂತ್ರಜ್ಞ. ಸೃಜನಶೀಲ ಚಿಂತನೆ ಮತ್ತು ಡೇಟಾ-ಸೂಚಿತ ನಿರ್ಧಾರಗಳಿಗೆ ಗುರುತಿಸಲ್ಪಟ್ಟವರು, ಅವರು ವೇಗದ ಪರಿಸರಗಳಲ್ಲಿ ಯಶಸ್ವಿಯಾಗುತ್ತಾರೆ ಮತ್ತು ಪ್ರೇಕ್ಷಕರೊಂದಿಗೆ ಆಳವಾಗಿ ಸಂಪರ್ಕಿಸುವ ಕಥೆಗಳನ್ನು ನಿರ್ಮಿಸುತ್ತಾರೆ.',
  }
};

export const LanguageProvider = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState(() => {
    const savedLanguage = localStorage.getItem('language');
    return savedLanguage || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', currentLanguage);
    document.documentElement.lang = currentLanguage;
  }, [currentLanguage]);

  const t = (key) => {
    return translations[currentLanguage][key] || translations.en[key] || key;
  };

  const changeLanguage = (language) => {
    setCurrentLanguage(language);
  };

  const value = {
    currentLanguage,
    changeLanguage,
    t,
    translations
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};
